baseurl: https://cciy.github.io
languageCode: zh-cn
theme: hugo-theme-stack
paginate: 5
title: Double`C Blog

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack
#    åšå®¢ç›®å½•ä¸­ä½¿ç”¨ç‰¹æ®Šå­—ç¬¦ï¼ˆ#ï¼Œ=ç­‰ï¼‰
preserveTaxonomyNames: true

# GA Tracking ID
googleAnalytics:

# Theme i18n support
#relURL: å°†è¾“å…¥å€¼è½¬æ¢ä¸ºç›¸å¯¹è·¯å¾„çš„url
#absURL: å°†è¾“å…¥å€¼è½¬æ¢ä¸ºç»å¯¹è·¯å¾„çš„url
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
DefaultContentLanguage: zh-cn

permalinks:
  #    åšå®¢å­˜æ”¾åœ°å€
  post: /:slug/
  page: /:slug/

params:
  mainSections:
    - post
  #ç‰¹è‰²å›¾ç‰‡ä½¿ç”¨çš„å­—æ®µï¼Œé»˜è®¤ä¸º imageã€‚ä¸å»ºè®®ä¿®æ”¹ã€‚
  featuredImageField: image
  #RSS è¾“å‡ºæ–‡ç« å®Œæ•´å†…å®¹
  rssFullContent: true
  #ç«™ç‚¹çš„å›¾æ ‡ï¼Œéœ€è¦å°†head.htmlä¸­çš„
  favicon: icon/site-icon.svg

  footer:
    since: 2020
    customText:

  dateFormat:
    published: 2006å¹´01æœˆ02æ—¥
    lastUpdated: 2006å¹´01æœˆ02æ—¥ 15:04 CST

  sidebar:
    emoji: ğŸ˜‰
    #ç«™ç‚¹ä»‹ç»
    subtitle: å­¦ä¹ æˆé•¿è®°å½•.
    #ä¸ªäººå¤´åƒ
    avatar:
      local: true
      src: img/avatar.png

  article:
    math: false
    license:
      enabled: true
      default: Licensed under CC BY-NC-SA 4.0

  comments:
    #        æ˜¯å¦åœ¨æ–‡ç« åº•éƒ¨é»˜è®¤æ˜¾ç¤ºè¯„è®ºç³»ç»Ÿ
    enabled: true
    provider: disqusjs
    disqusjs:
      shortname: https-cciy-github-io
      apiUrl: https://cciy.github.io/
      apiKey: IdMMTBWQaYotIfmfLed6forHU8460bQpiUGuYksfti5HHHSQdPvyQKqdN8SUFwlp
      admin: cc
      adminLabel:
    utterances:
      repo: cciy/hugo-comment
      issueTerm: pathname
      label:

    remark42:
      host:
      site:
      locale:

    waline:
      path: location.pathname  # å…¨å±€è¯„è®ºåœ°å€
      serverURL:
      meta: nick,mail,link # waline comment header info
      requiredFields: [ 'nick','mail' ]
      placeholder: å¿«æ¥è¯„è®ºå§~  # è¯„è®ºå ä½æç¤º
      avatar: robohash # gravatarå¤´åƒ
      avatarCDN: https://sdn.geekzu.org/avatar/ #ä¸å»ºè®®ä½¿ç”¨loliæº
      pageSize: 10 # è¯„è®ºæ¯é¡µæ˜¾ç¤ºæ•°é‡
      lang: zh-CN



  widgets:
    enabled:
      - search
      - archives
      - tag-cloud

    archives:
      limit: 5

    tagCloud:
      limit: 10

    categoriesCloud:
      limit: 20

  opengraph:
    twitter:
      # Your Twitter username
      site:

      # Available values: summary, summary_large_image
      card: summary_large_image

  defaultImage:
    opengraph:
      enabled: false
      local: false
      src:

  colorScheme:
    # Display toggle
    toggle: true

    # Available values: auto, light, dark
    default: auto

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
#å¯¼èˆªæ 
menu:
  main:
    - identifier: home
      name: ä¸»é¡µ
      url: /
      weight: -100
      pre: home


related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100

    - name: categories
      weight: 200

#é…ç½®è§https://gohugo.io/getting-started/configuration-markup/#goldmark
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    noClasses: false
    lineNumbersInTable: true
  #    æ˜¯å¦æ˜¾ç¤ºè¡Œ
    linenos: true
    tabWidth: 4
  #        å†…å®¹ç›®å½•è¡¨æ ¼
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  goldmark:
    renderer:
      hardWraps: false
      #            é»˜è®¤æƒ…å†µä¸‹ï¼ŒGoldmarkä¸å‘ˆç°åŸå§‹HTMLå’Œæ½œåœ¨å±é™©çš„é“¾æ¥ã€‚å¦‚æœæ‚¨æœ‰å¾ˆå¤šå†…è”HTMLå’ŒJavaScriptï¼Œåˆ™å¯èƒ½éœ€è¦æ‰“å¼€å®ƒã€‚
      unsafe: true
      xhtml: false
#æ¨¡å—é…ç½®ï¼šhugoVersio(extended:æ˜¯å¦éœ€è¦æ‰©å±•ç‰ˆæœ¬çš„Hugo)
module:
  hugoVersion:
    extended: true